modLoader="javafml"
license="MIT License https://github.com/McJtyMods/LostCities/blob/1.16/LICENCE"
loaderVersion="[2,)"
issueTrackerURL="http://github.com/McJtyMods/LostCities/issues"
displayURL="http://github.com/McJtyMods/LostCities/"
#logoFile="examplemod.png" #optional
#credits="Thanks for this example mod goes to Java" #optional
authors="McJty"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[mods]]
modId="lostcities"
version="${file.jarVersion}"
displayName="LostCities"
#updateJSONURL="http://myurl.me/" #optional
description='''
Generate cities all over the world
'''
[[dependencies.lostcities]]
modId="neoforge"
type="required"
versionRange="[20.4,)"
ordering="NONE"
side="BOTH"
